### ISSUE TITLE
"Open containing folder" should highlight the file in the containing folder if opening a single-file torrent

### ISSUE THREAD

**Issue by lighterowl** [xavery/transgui#104]
Originally reported by @devnoname120 in #101 .

> If I click on `Open containing folder` on a single-file torrent (`audiobook.m4b`) then it opens Finder on the directory of all completed files (in my case `/mnt/torrents/completed`) without highlighting the specific one that I was looking for, so I have to scan the list of files in the directory myself or use the search to find `audiobook.m4b`. It would be nice if it were highlighted in the Finder window that transgui opens.

I can see the same behaviour under Linux+xfce+Thunar, but not Windows, where the file is highlighted in the new Explorer window.

**Comment by lighterowl** [comment]
macOS solution is in https://stackoverflow.com/questions/7652928/launch-finder-window-with-specific-files-selected , see if I can figure out how to call the ObjC function, otherwise settle on `open -R`.

**Comment by lighterowl** [comment]
Doing the same on Linux will require making a DBus call to something implementing https://www.freedesktop.org/wiki/Specifications/file-manager-interface/ .

**Comment by devnoname120** [comment]
> macOS solution is in [stackoverflow.com/questions/7652928/launch-finder-window-with-specific-files-selected](https://stackoverflow.com/questions/7652928/launch-finder-window-with-specific-files-selected) , see if I can figure out how to call the ObjC function, otherwise settle on `open -R`.

Awesome, thanks for looking into it :)

**Comment by lighterowl** [comment]
`Open containing folder` will now always show the containing folder of the given item in the platform's local file manager, with the item - whether a folder or a file - highlighted in that folder. This applies to individual torrents in the program's main table as well as their contents in the `Files` tab.

**Comment by lighterowl** [comment]
https://github.com/transmission-remote-gui/transgui/issues/1462
