### ISSUE TITLE
"Accessibility > Text size" setting on Windows is not honoured

### ISSUE THREAD

**Issue by lighterowl** [xavery/transgui#107]
Originally reported in #103 .

`tl;dr` Changing this setting :
![369674269-dc7f2a9f-8900-49a8-a017-a74b8a4efc86](https://github.com/user-attachments/assets/89e1a9f4-029e-4ca4-a005-cf735688b2a1)

does not affect transgui's font size at all.

**Comment by lighterowl** [comment]
Posted a question in the [Lazarus forums](https://forum.lazarus.freepascal.org/index.php/topic,68637.0.html) as I'm completely clueless at this point.

**Comment by lighterowl** [comment]
Fixed in fc734b1d5fac33a5c6b431de4575d5a695f92288 .

**Comment by lighterowl** [comment]
@SESNut Please try out this build : https://github.com/lighterowl/transgui/actions/runs/11038065872/artifacts/1978268557

**Comment by SESNut** [comment]
:thumbsup:
