### ISSUE TITLE
Window constantly moving on start-up, causes "vibration" effect

### ISSUE THREAD

**Issue by Mrnofish** [xavery/transgui#112]
When starting 5.18.7f, build a3cf81e under Windows 10, with the window maximized, instead of taking up the whole available space, the window seems slightly offset to the right and down, and enters a loop of constantly moving around by a small amount, which results in an effect, as if the window was vibrating.

Maximizing the window interrupts the loop and the application is good after that, but the problem will reappear as soon as the application is closed and restarted.

**Comment by lighterowl** [comment]
Sounds very similar to #38.

**Comment by Mrnofish** [comment]
Whoops, sorry!
