### ISSUE TITLE
Labels can't be removed - `Labels can't be empty`

### ISSUE THREAD

**Issue by Beersteddy** [xavery/transgui#17]
Transmission 4.0.3 LSIO docker container
transgui v5.18.0.f windows

Steps:
- Assing any label to a torrent (F7)
- 
![image](https://user-images.githubusercontent.com/91010735/236827511-ef20b9f4-aa15-4bb2-9509-3e94501ab7d6.png)

- Finish adding it
- Go back to torrent, try to remove the label by living the field empty
![image](https://user-images.githubusercontent.com/91010735/236826926-3a107da1-646b-4366-854a-430d917d08a9.png)

- errors appears `labels cannot be empty` contradicting the previous window
- labels will not be removed
-  ![image](https://user-images.githubusercontent.com/91010735/236827032-d75ab369-5c48-41ac-a3ac-e3deec532d4d.png)

**Comment by xavery** [comment]
Thanks for the report. This message seems to be coming from the server itself (`rpcimpl.cc`, line 986), so perhaps something changed between 3.0 and 4.0 when it comes to processing labels. I'll see what I can do.

**Comment by xavery** [comment]
The freshly released v5.18.1.f includes a fix for this.

**Comment by Beersteddy** [comment]
Tested and can confirm that the issue is fixed.

Thanks for solving this ultra-fast
