### ISSUE TITLE
Ctrl+C to copy torrent name / filenames - feature request

### ISSUE THREAD

**Issue by Beersteddy** [xavery/transgui#20]
Any chance to have an option in the config to add a shortcut to copy selected torrent names in the main window and/or file name(s) when files selected  in `torrent file list` 

example setting:
`CopyName=Ctrl+C`

![image](https://github.com/xavery/transgui/assets/91010735/f424e2b2-4246-4695-8fc8-1857e6e0c8ae)

**Comment by xavery** [comment]
Thanks for the report.

I chose not to do this as a customisable keyboard shortcut and just use the platform's default "copy key sequence" instead, which means Ctrl-C on Windows and Linux and Command-C on macOS.

I think I have something that works, can you download and test https://github.com/xavery/transgui/suites/12872584095/artifacts/694367702 to see if the changes are OK?

**Comment by Beersteddy** [comment]
> Thanks for the report.
> 
> I chose not to do this as a customisable keyboard shortcut and just use the platform's default "copy key sequence" instead, which means Ctrl-C on Windows and Linux and Command-C on macOS.
> 
> I think I have something that works, can you download and test https://github.com/xavery/transgui/suites/12872584095/artifacts/694367702 to see if the changes are OK?

It works... almost as expected.

Copying torrent name works exactly as expected - `linux.iso` is copied 
Copying file name not exactly - `/path/to/linux.iso is getting copied, instead of just `linux.iso`

**Comment by xavery** [comment]
OK. The paths now will now be copied relative to the torrent's root without including the save folder name, i.e. you will get `file1.txt`, `file2.txt`, `folder1/file3.txt` etc for multi-file torrents.

The new build is here : https://github.com/xavery/transgui/suites/12886324416/artifacts/695327989

**Comment by Beersteddy** [comment]
And it works exactly as expected.

Thanks for adding this functionality super fast.

I'm gonna create one more request/bugfix (sorting). Hope you don't mind.

**Comment by xavery** [comment]
@Beersteddy Of course I don't, keep 'em coming.
