### ISSUE TITLE
Add Torrent has wrong keyboard shortcut showing

### ISSUE THREAD

**Issue by wally-crunk** [xavery/transgui#21]
5.18.0f on Mac OS Ventura 13.3.1:

The "Add Torrent" and "Add Torrent Link..." command in the file menu both show a keyboard shortcut that is tofu:

<img width="332" alt="Screenshot 2023-05-09 at 12 54 40 PM" src="https://github.com/xavery/transgui/assets/122107861/099b4db9-ab09-49cd-9fcd-a6c2bf77c692">

Also, the About box copyright notice should more clearly show the forked author's name (or psudonym) **_not_** just the original authors.

**Comment by xavery** [comment]
Thanks for the report. This also happens on Big Sur 11.7.4.

That shortcut is supposed to be the `Insert` key. I don't have a real Mac keyboard so I wasn't even aware that it doesn't have that key. Can you suggest a sensible alternative? Perhaps `F2` could be one, seeing how all the other shortcuts are defined.

**Comment by Beersteddy** [comment]
F2 probably is not the best idea as it's used already for renaming, at least on windows.

F5 doesn't seems to be assigned to anything.

**Comment by xavery** [comment]
Replaced with F5.
