### ISSUE TITLE
Support multi-selection in filtering

### ISSUE THREAD

**Issue by xavery** [xavery/transgui#24]
Multi-selection should be supported in filters by matching any element of the selected subgroups (statuses, folders, trackers, labels) and ANDing those expressions.

For example, selecting `Downloading` and `Active` in statuses, `foobar` in folders, `mytracker1.org` and `mytracker2.org` in trackers, and `a`, `b` and `c` in labels should show all torrents that :

- are either in `Downloading` or `Active` states,
- *and* their destination folder is `foobar`,
- *and* they're using either `mytracker1.org` or `mytracker2.org`,
- *and* they were assigned any of `a`, `b`, `c` labels.

**Comment by Beersteddy** [comment]
This would be absolutely amazing if can be extended to trackers as well. One of the functions I have never seen on any other torrent client
