### ISSUE TITLE
Max peers per torrent is missing from preferences

### ISSUE THREAD

**Issue by Pentaphon** [xavery/transgui#35]
Can we have the Max peers per torrent setting? There's only the global peer limit at the moment.

**Comment by Pentaphon** [comment]
> Is it this option here?

Not exactly. We should have that option in the main preferences window to affect all torrents at the same time, not just one at a time.

**Comment by Pentaphon** [comment]
> You can mark multiple (or all) torrents and then use this option. It will affect all selected torrents.

Seems easier to just use the preferences window. Why leave that setting out when its on the original client?

**Comment by xavery** [comment]
Agreed, no reason why it shouldn't be here as well. What @fredo-47 described will work for all current torrents but the difference is that setting `peer-limit-per-torrent` globally will also affect any new added torrents.
