### ISSUE TITLE
native apple silicon build

### ISSUE THREAD

**Issue by jata1** [xavery/transgui#41]
@xavery - dzieki from Sydney for working on this project. My wife is polish!

I have a M2 Mac but when I try to use the latest release build, I need to install rosetta so it is not native apple silicon.

Are you able to create a apple silicon build easily or am I best to continue to use the version from the community build/fork.

Thanks again.
Jago

**Comment by xavery** [comment]
Hi, thanks for the kind words.

Support for Apple Silicon was just merged yesterday and there is no official (tagged) release out yet. If you want, you can try out the development build : https://github.com/xavery/transgui/suites/14655163568/artifacts/831550754

**Comment by k0ste** [comment]
I installed the new build from artifacts, runs fine. Seems works smoother than previous year build from @shermanikk
Hope some day somebody merge this changes to origin repo 🦄

**Comment by jata1** [comment]
> Hi, thanks for the kind words.
> 
> Support for Apple Silicon was just merged yesterday and there is no official (tagged) release out yet. If you want, you can try out the development build : https://github.com/xavery/transgui/suites/14655163568/artifacts/831550754
> 
> Unless this is what you tried, in which case I'll investigate though it will be hard as I have Rosetta installed on my M1 host and no way to uninstall it (as it requires launching the computer in recovery mode which I cannot do as it's a remote host).

Thank you. I did not realise I needed to get the dev build. I will try again but looks like I dev build is working. 

I also hope this good work is merged back to the main project.

**Comment by jata1** [comment]
tested and working fine on my M2 Mac. thanks again.

**Comment by xavery** [comment]
`v5.18.3f` is now released with these changes - closing.

**Comment by jata1** [comment]
Thank you.
