### ISSUE TITLE
Enable Select-All Keyboard Shortcut for Search Field

### ISSUE THREAD

**Issue by Horridge** [xavery/transgui#43]
Thank you for your work in keeping TransGUI ticking along. I'd like to request a quality of life improvement.

After searching for a torrent within Transmission Remote GUI search field, my default behaviour is then to Ctrl-A / Select-All, so I can search for a different string or just delete the existing string. However the keyboard shortcut will select-all filtered torrents. 

I would expect if the search field is selected then Ctrl-A will select the search string, and if the torrent list is selected, Ctrl-A would then select-all filtered torrents.

**Comment by xavery** [comment]
Thanks for the report. I agree that Ctrl-A should perform a "Select All" in the search field when it has focus.

**Comment by xavery** [comment]
This is now implemented.

I also found out that the search box has a special binding for the `Esc` key : pressing it clears the input field completely. Seems like this would be much easier for what you want to do.
