### ISSUE TITLE
Keyboard shortcuts are weird on macOS

### ISSUE THREAD

**Issue by xavery** [xavery/transgui#45]
https://github.com/transmission-remote-gui/transgui/issues/1355#issuecomment-1671764154

Generally, transgui keyboard shortcuts are hardcoded to use Ctrl. The idea is to switch Ctrl to Command when running on macOS, and hope that they don't clash with any globally defined/OS-standard keyboard shortcuts.

Sadly I don't think there's a uniform way to do this in Lazarus, as the widget/action definitions (and those are used a lot here) can have only one `ShortCut` set, so any solution is going to involve rewriting those at runtime once we realise we're running on macOS.

**Comment by xavery** [comment]
The first build with these changes, which pretty much convert all `Ctrl+something` keyboard shortcuts to `Command+something` is available here : https://github.com/xavery/transgui/suites/16011543153/artifacts/913895959

Please try it out and comment.

**Comment by Smultie** [comment]
Seems to work fine! Thanks for fixing this!
