### ISSUE TITLE
[improvement] Remove "www" and "tracker" from tracker name

### ISSUE THREAD

**Issue by Beersteddy** [xavery/transgui#53]
Tracker names have already `https://` removed from the name but "www" and "tracker" is still there
examples
`https://firstone.io` will be displayed as `firstone.io` on trackers list
`https://tracker.firstone.io` = `tracker.firstone.io`
`https://www.tracker.firstone.io` = `www.tracker.firstone.io`

Any chance to get rid of "www" and "tracker" to make the list cleaner?

**Comment by xavery** [comment]
Thanks for the report.

As far as I remember, Transmission's own Qt client does the same thing so why not have it here as well.

**Comment by Beersteddy** [comment]
Yes. TM GUI removes it already

**Comment by Beersteddy** [comment]
Quickly done!

Where can I find windows build to test it?

**Comment by xavery** [comment]
@Beersteddy Have a look here : https://github.com/xavery/transgui/suites/16102213730/artifacts/919252569

**Comment by Beersteddy** [comment]
> @Beersteddy Have a look here : https://github.com/xavery/transgui/suites/16102213730/artifacts/919252569
Looks much better without www.

So far so good. Not a single problem

**Comment by Beersteddy** [comment]
> @Beersteddy Have a look here : https://github.com/xavery/transgui/suites/16102213730/artifacts/919252569

It looks like this change caused the problem below - `key not in map`
An error window appears very often when clicking on a tracker name.

![image](https://github.com/xavery/transgui/assets/91010735/9c5ae27c-2f26-4fde-8307-903f52f5bcf6)

**Comment by xavery** [comment]
> > @Beersteddy Have a look here : https://github.com/xavery/transgui/suites/16102213730/artifacts/919252569
> 
> It looks like this change caused the problem below - `key not in map` An error window appears very often when clicking on a tracker name.
> 
> ![image](https://user-images.githubusercontent.com/91010735/270117022-9c5ae27c-2f26-4fde-8307-903f52f5bcf6.png)

This is most likely caused by #48 as I removed a good chunk of exception-swallowing code there. I think I know what the issue might be but will need to look into it in detail and reproduce it locally first.

**Comment by Pentaphon** [comment]
@xavery Here's some more you can filter out to make the list cleaner:

`bt` for bittorrent
`t` for tracker
`tk` for tracker
`tr` for tracker
`opentracker` for URLs using that software
`open` for a shortened version of the above.

See https://github.com/qbittorrent/qBittorrent/issues/19851 for the issue on qBittorrent and https://github.com/openscopeproject/TrguiNG/issues/51 for what TrguiNG currently does to filter it.
