### ISSUE TITLE
httpsend

### ISSUE THREAD

**Issue by hallonstedt** [xavery/transgui#6]
I may be doing this wrong but I am trying to compile the binary on Windows 10 x64.
I unpack the files, successfully run install_deps.bat and then when I run make_setup.bat I get the following error:
```
(3104) Compiling main.pas
E:\transgui-master\main.pas(46,65) Warning: (3226) Don't load LINEINFO unit manually, Use the -gl compiler switch instead
E:\transgui-master\main.pas(44,3) Fatal: (10022) Can't find unit httpsend used by Main
Fatal: (1018) Compilation aborted
```
Any suggestions on how to resolve this?

**Comment by xavery** [comment]
`synapse` is now a submodule. Make sure you do `git submodule update --init --recursive` after cloning the main repository.

**Comment by hallonstedt** [comment]
Thank you! 

I have no clue how to compile on windows so now I'm happy. It still says version 5.18.0 but the compiler versions are updated so I think we're good. You may want to add a version tag to indicate it's your artifact.

You may also want to mention there are pre-compiled versions under Actions / windows build. To a novice, it's not obvious as we usually only look for published releases.

**Comment by xavery** [comment]
I will post them as releases once they're ready. This should still be considered pre-release even though, as you've noticed, the compilation is already done with newer FPC and Lazarus versions.
