### ISSUE TITLE
Changing filtering to wider one doesn't scroll list to selected torrent.

### ISSUE THREAD

**Issue by blacklion** [xavery/transgui#63]
When list of torrents is filtered (say, "Downloading" status) and some torrent is selected in list, in classical transgui you could switch to other filtering, and if this torrent is still visible (for example, switch to "All") list is scrolled to this torrent and it selected and current.

This fork shows data for new torrent in bottom panel, but don't scroll list to it, showing new list from position 0.

Maybe, related to #62.

**Comment by xavery** [comment]
Pretty sure this is caused by the change made to fix #25.

However that ticket (as originally specified) only concerns sorting so one could argue that automatically applying the same behaviour when filtering is a bug. Perhaps there is a way to turn it on when sorting but keep it off when filtering/adding.

**Comment by blacklion** [comment]
@xavery I think fixing #25 is a big mistake. Current "official" GUI build always left current torrent selected and it is VERY useful in many situations.

For example: you have torrents sorted by size, but want to see torrents with names similar to THIS torrent. You select THIS torrent and sort by name - you see all similar names, as THIS torrent still selected!

To go to top of the list you don't need to "scroll" you need to press "Home" button on keyboard.

IMHO, old behavior is much, much better.

But your build is so much responsive with large number of torrents (2K+) and slow connection to daemon...

**Comment by xavery** [comment]
@blacklion I actually like the new behaviour, though I see your point. Would you be happy if this is added as a configuration option so you can tick a check-box and have the old behaviour back?

**Comment by blacklion** [comment]
Configurable is always good! Thank you!

**Comment by xavery** [comment]
@blacklion The latest build has a new option in the "View" menu :

![Screenshot_2023-11-22_23-00-57](https://github.com/xavery/transgui/assets/127875/5773bf6d-a46f-404a-965e-2b16438c7d41)

Please select it and test stuff out, all behaviour should be back to classic. The setting is saved in the INI file so once you set it you can forget all about it and just enjoy the old behaviour.

Not sure which platform you're running so here's links to all builds : [Windows](https://github.com/xavery/transgui/suites/18427097888/artifacts/1068097271), [Linux](https://github.com/xavery/transgui/suites/18427097886/artifacts/1068095775), [macOS](https://github.com/xavery/transgui/suites/18427097876/artifacts/1068096686).

**Comment by blacklion** [comment]
It works, thank you!
