### ISSUE TITLE
Menus from Mac OS top menu bar mistakenly disappeared

### ISSUE THREAD

**Issue by fab442** [xavery/transgui#72]
Hi,
I am a Mac user of Transmission remote GUI. I unticked the "menu" from the "view" dropdown menu of the app on my Mac. I am stuck with a menuless and useless app... My mistake! I tried uninstalling Transmission remote GUI and reinstalling through homebrew. Didn't work. Then I found this repository, I installed transgui, and I got exactly the same problem... Obviously the two apps share the same settings file. I looked through the "preferences" folder of my Mac and could delete one or two files but it didn't restore the default settings. Can anyone tell me where the settings file is located on Mac OS please ?

This is my app right now...
<img width="1512" alt="281707050-af3547a7-8cc9-41de-895b-0b477a2de1c7-1" src="https://github.com/xavery/transgui/assets/78967210/04e9aac0-8c9f-4721-8e39-eab845c23bb2">

Thanks guy,
Fab

PS : I originally created this topic before knowing about this repo. https://github.com/transmission-remote-gui/transgui/discussions/1464

**Comment by lighterowl** [comment]
Hi Fab.
The configuration file path is `$HOME/.config/Transmission Remote GUI/transgui.ini`. Open it with a text editor and change `Menu=0` to `Menu=1` in the `[MainForm]` section.

Alternatively, you can try pressing `Command-F12` in the main window as that's the default shortcut for showing/hiding the menu bar.

**Comment by fab442** [comment]
Problem solved, thank you very much !!
