### ISSUE TITLE
Total statistics not shown in bottom bar

### ISSUE THREAD

**Issue by iatacs19** [xavery/transgui#78]
This information seems to be missing compared to the original program:
![transmission GUI original](https://github.com/xavery/transgui/assets/33841205/e87e9b93-2e13-4caa-85d4-4c85dbd162a8)

The current xavery release:
![transmission GUI new](https://github.com/xavery/transgui/assets/33841205/750a1343-a0ef-4399-acc6-f8ce54d86c77)

The file it gets the information from is named `stats.json`

**Comment by lighterowl** [comment]
Hi there, sorry, can't reproduce I'm afraid.

Are you sure `Status bar - Sizes` is checked in the `View` menu?

**Comment by iatacs19** [comment]
You are right! I'm so sorry I didn't have that option enabled.

**Comment by iatacs19** [comment]
You are right! I'm so sorry I didn't have that option enabled.
