### ISSUE TITLE
Font sizes less than 100% mess up the Applications Setting dialog

### ISSUE THREAD

**Issue by wally-crunk** [xavery/transgui#86]
As per the title.  Font sizes below 100% on Mac OS cause the dialog "sub grouping boxes" to be too small.

This is a longstanding bug.

![1](https://github.com/lighterowl/transgui/assets/122107861/7262ce9b-0a83-417c-9826-760893a4ed76)
![2](https://github.com/lighterowl/transgui/assets/122107861/974d8c21-5887-4878-80c7-2f9bef49c0f8)

**Comment by lighterowl** [comment]
Thanks, realistically this isn't solvable until somebody with much more patience than me re-does the dialogs (which currently all use absolute positioning) and takes a serious look at all the custom sizing code.

**Comment by lighterowl** [comment]
https://github.com/transmission-remote-gui/transgui/issues/1432

**Comment by lighterowl** [comment]
e6ca4982b441f278561330dcc54ba88a83bcaa40 removes the code that made implementing this option possible, so the option itself is removed too.

From now on, setting a custom scaling factor inside the application is not supported. The application will (or, at least, should, and did in my testing) use the same scaling settings as the OS that it's running on.
