### ISSUE TITLE
Check for new version: 301

### ISSUE THREAD

**Issue by k0ste** [xavery/transgui#87]
Seems account name was changed, can you make a new release to fix this?
<img width="259" alt="Screenshot 2024-06-29 at 13 22 42" src="https://github.com/lighterowl/transgui/assets/7759548/77f9e29b-75f2-4716-a828-cd3e42da5400">

**Comment by pwinn** [comment]
xavery is now @lighterowl, and the client update-checker doesn't seem to handle 301 redirects.

**Comment by pwinn** [comment]
Looks like `about.pas` line 198 has the old URL, needs to be changed to `'https://api.github.com/repos/lighterowl/transgui/releases/latest'`. 

Ideally, lines 198-206 should be updated to handle 301 redirects better, but at least updating the URL will resolve the current issue.

**Comment by pwinn** [comment]
As far as I can tell, Synapse 40 does not support redirects, so explicit handling of `FHttp.ResultCode = 301` would need to be added, or really any ResultCode beginning with `3`.

**Comment by lighterowl** [comment]
Thanks. GitHub was the last place where my old handle was used and I finally decided to change it. Unfortunately, I forgot about my transgui fork which had the URL to my old account baked-in.

> As far as I can tell, Synapse 40 does not support redirects, so explicit handling of `FHttp.ResultCode = 301` would need to be added, or really any ResultCode beginning with `3`.

Yup, looks like it. Interestingly, Free Pascal provides a module called [fphttpclient](https://wiki.lazarus.freepascal.org/fphttpclient) which supports redirects and support for that is even described on the wiki page.

**Comment by lighterowl** [comment]
5.18.5.f released with the fix. Closing.
