### ISSUE TITLE
gui cannot add torrent file on macos sonoma

### ISSUE THREAD

**Issue by ywj070101526** [xavery/transgui#98]
unable to select torrent file
![WechatIMG681](https://github.com/user-attachments/assets/2edb4885-c6e0-42f8-97aa-7fc09d0afdfc)

**Comment by lighterowl** [comment]
Worksforme. https://github.com/user-attachments/assets/d8b630e2-3da8-4a53-8c15-da0f0084f72d

As noted in the readme, macOS isn't one of my primary platforms so maybe somebody else can offer some insight.

**Comment by devnoname120** [comment]
Works for me as well on Apple M1 running `Sonoma 14.5`.
I haven't tried with `Sonoma 14.6.1` yet.

**Comment by lighterowl** [comment]
Closing as no reply for over a week.
